### ISSUE TITLE
Ensure we have github usernames in contact fields for all apis

### ISSUE THREAD

**Issue by cmungall** [NCATS-Tangerine/translator-api-registry#2]

**Comment by cmungall** [comment]
@kevinxin90 will add as exemplars to some of the existing yamls

**Comment by newgene** [comment]
@cmungall the "info.contact.x-id" extension field now supports a list (can be either one item or a list), where you can add github user URL. 


    x-id:
      - 'http://orcid.org/0000-0002-2629-6124'
      - 'https://github.com/newgene'

and 

    x-id: 'https://github.com/newgene'

are both valid.

A complete example [here](https://github.com/NCATS-Tangerine/translator-api-registry/blob/master/mygene.info/openapi_minimum.yml).
