### ISSUE TITLE
Tests are failing on master

### ISSUE THREAD

**Issue by patrickkwang** [NCATS-Tangerine/translator-api-registry#32]
Something seems to have gone awry with a recent push:
https://github.com/NCATS-Tangerine/translator-api-registry/commit/66676ee9316b98049279b9d93b2676b755e5f9bc
Apparently the GTex API is missing the `tags` field. It also appears to be a JSON file with a .yaml extension, so I'm not sure quite how that's supposed to be handled.

To avoid this in the future, an owner of the repo could protect the master branch and enforce that tests must be passing before anything can be merged in. @newgene, do you have the power to do that?

**Comment by PhillipsOwen** [comment]
Corrected and tested.
