### ISSUE TITLE
Add link to swagger v2->v3 converter to README

### ISSUE THREAD

**Issue by cmungall** [NCATS-Tangerine/translator-api-registry#4]

**Comment by newgene** [comment]
Here is the link:

http://openapi-converter.appspot.com/

(code: https://github.com/Mermade/swagger2openapi)

Not perfect, but can be a good starting point to convert your existing swagger v2 specs.

Will add this to the README doc.

**Comment by newgene** [comment]
updated README in 3b572c288e07b9d17a6f7919cad4c281403c14b7
